version: '3.8'

services:
    dev_api:
        container_name: aprego_dev_api
        image: nestjs-api-dev:1.0.0
        build: .
        entrypoint: sh -c "yarn && yarn start:dev"
        ports:
            - 3000:3000
        volumes:
            - .:/home/node/app
            - /home/node/app/node_modules
        restart: unless-stopped